### ISSUE TITLE
code search[BUG]: 

### ISSUE THREAD

**Issue by sheashaa2019** [yrestom/POS-Awesome#101]
### Versions
ERPNext: v12.27.0 (version-12)

Frappe Framework: v12.24.0 (version-12)

POS Awesome: v3.1.1 (master)

### What is actually happening?
when search for item code The search result appears with the names of the items that contain the number, not the item itself. It does not appear
![test](https://user-images.githubusercontent.com/53827660/147678767-4f4f13c7-af8a-4581-874b-5a66a544a246.jpg)

**Comment by bkm888** [comment]
I believe this has already been fixed in v3.2.1
The problem was the search order. The search would start searching names first so if it came across the numeric values in a name it would stop the search and display what it had found.

The search order now I believe is Item Code > Barcode > Item Name

This is working on my v3.2.1 implementation.

BKM :)
