### ISSUE TITLE
[BUG]: Partial Payment not working on sales Order

### ISSUE THREAD

**Issue by winchai** [yrestom/POS-Awesome#127]
### Versions

ERPNext: v13.19.0 (version-13)
Frappe Framework: v13.19.0 (version-13)
POS Awesome: v3.1.1 (master)

### Steps to reproduce

1. Go to 'POS Awesome and Create a Pos Profile with Partial Payment and Create Sales Order Enabled'
2. Create Sales Order using Pos Awesome with Payment About 50% of the invoice portion
3. Go To Selling --> Sales Order and Click Sales Order we created earlier
4. Scroll Down To See the payment submitted are 100% of the Invoice Portion

### What is Expected?

Payment should be according to POS payment

### What is actually happening?

Payment always 100% of the invoice portion
 
### Screenshot
<img width="525" alt="POSAWESOMEBUG 1" src="https://user-images.githubusercontent.com/58699787/153691172-e002f3a7-fef1-4f0c-a559-a386b85407dc.png">
<img width="1090" alt="POSAWESOMEBUG" src="https://user-images.githubusercontent.com/58699787/153691181-a1451200-b7af-4762-8106-b45c76184cfb.png">

**Comment by karanwilson** [comment]
Hi, was this issue resolved ?

**Comment by yrestom** [comment]
I didn't find a way to solve it
Because the application always calculates the payment schedule in the sales order without verifying the amount paid in the sales invoice
You can review the code here
https://github.com/frappe/erpnext/blob/35c71f5923a05d576bcb9608b87b1ffaf1d2743f/erpnext/controllers/accounts_controller.py#L1557
