### ISSUE TITLE
Rounding Total

### ISSUE THREAD

**Issue by bobzz-zone** [yrestom/POS-Awesome#22]
Hi

i think we have issue with rounding...

since we need to round it at the same method with ERPNext POS will do...

thanks

**Comment by bobzz-zone** [comment]
@yrestom any update on tis ?.. or a clue where i can imporve it ?

**Comment by yrestom** [comment]
Can you provide more details about this issue and it will be better if you use this [issue template](https://github.com/yrestom/POS-Awesome/edit/master/.github/ISSUE_TEMPLATE/bug_report.md):

**IMPORTANT** Before reporting a bug:

A properly detailed bug report can save a LOT of time and help to fix issues as soon as possible.
- ->

### Versions

- Frappe: 
- Erpnext: 
- POS Awesome: 

### Stacktrace / full error message

```javascript
(paste here)
```

### Steps to reproduce

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

### What is Expected?


### What is actually happening?


### Additional context
Add any other context about the problem here.


### Screenshots
If applicable, add screenshots to help explain your problem.

**Comment by bobzz-zone** [comment]
Hi,

this is not a bugs , but i think its more clasified that feature that must have

![image](https://user-images.githubusercontent.com/1543515/104672770-ff594380-5712-11eb-8c9c-be3129f973d9.png)
**What To Expect **
we need to add rounding total in this section , and the total below need to be rounded.. so the total can be replaced with the grand total
in my country or some country , prices need to be rounded for example in my country it should be 100 is the minimum , becuse if below 100 there is no exchange for the customer

**Comment by yrestom** [comment]
You can check here:
https://github.com/yrestom/POS-Awesome/blob/9f2548c0f10fd1aefa04ce251359ff43f482ee96/posawesome/public/js/posapp/components/pos/Invoice.vue#L349

**Comment by bobzz-zone** [comment]
Hi,

is that ok if i hide the total qty field?

and where should i calculate the write off value so it can be fetched into the field ?
