### ISSUE TITLE
[BUG]: Accordion in cart not displaying, without doing any update or changes  server on ubuntu 22.04

### ISSUE THREAD

**Issue by tedyswaga** [yrestom/POS-Awesome#242]
- Erpnext: 
- POS Awesome: 

### Stacktrace / full error message

```javascript
(paste here)
```

**Comment by tedyswaga** [comment]
I think one of the stylesheet is usind  a cdn, i will investigate more and get back

**Comment by yrestom** [comment]
Thank you for reporting this issue! To help us investigate and resolve it quickly, could you please provide the following information:

1. Versions:
   - Frappe: [e.g., V14.13.0]
   - Erpnext: [e.g., V14.14.0]
   - POS Awesome: [e.g., V6.1.0]

2. Stacktrace / Full error message:
   ```
   [Paste the error message or stacktrace here]
   ```

3. Steps to reproduce:
   Please provide detailed steps to reproduce the issue, such as:
   1. Go to '...'
   2. Click on '...'
   3. Scroll down to '...'
   4. See the error

4. Expected behavior:
   Describe what you expected to happen.

5. Actual behavior:
   Explain what is currently happening instead.

6. Additional context:
   If there is any additional information or context related to the problem, please share it here.

7. Screenshots:
   If applicable, you can also include screenshots to help us better understand the problem.

Your cooperation in providing these details will be highly appreciated. It will allow us to investigate and resolve the issue more effectively. Thank you!
